version: '3'
services:
  beat:
    image: docker.elastic.co/apm/apm-server:7.1.1
    ports:
      - "8200:8200"
      - "8201:8200"
    environment:
      - apm-server.host=0.0.0.0
    volumes:
      - ./apm-server.yml:/usr/share/apm-server/apm-server.yml
    networks:
      - apm
    depends_on:
      - elasticsearch
      - kibana

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - ELASTIC_PASSWORD=WUHl8OGHl^nm
    networks:
      - apm
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - apm
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:7.1.1
    volumes:
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - apm
    depends_on:
      - elasticsearch


  db:
   #Acessa o repositorio localhost para usar a imagem
    image: mysql:latest
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=gestaoprojeto
      - MYSQL_DATABASE=gestaoprojeto
      - MYSQL_USER=gestaoprojeto
      - MYSQL_PASSWORD=gestaoprojeto
    volumes:
#cria volume persistente
      - dbdata:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
#reinicia o banco de dados caso haja algum problema de execução
    restart: always
    depends_on:
      - elasticsearch
      - kibana
      - beat
    networks:
      - apm
#persiste os dados do banco de dados em /var/lib/docker/volumes/*
volumes:
  dbdata:

networks:
 apm:
    driver: bridge



